version: '3'

services:
  wagtail:
    image: beobgrp_site:0.2
    environment:
      WAGTAIL_DB_PASSWORD: ${WAGTAIL_DB_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - wagtail_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: ${WAGTAIL_DB_PASSWORD}
      POSTGRES_DB: beobgrp_site
    ports:
      - "5432:5432"
    volumes:
      - /beobgrp_site/postgres:/var/lib/postgresql/data
    networks:
      - wagtail_network

networks:
  wagtail_network:

