version: '3.8'

services:
  registry:
    image: registry:latest
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ~/.docker-registry:/var/lib/registry
    networks:
      - registry-net
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./registry-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - registry
    networks:
      - registry-net

  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "127.0.0.1:8080:80"
    environment:
      REGISTRY_URL: http://localhost:5000
      DELETE_IMAGES: "true"
    networks:
      - registry-net

networks:
  registry-net:
